import React, { useState, useEffect } from 'react';
import { 
  X, 
  ChevronRight, 
  ChevronLeft, 
  Target, 
  Layout, 
  Type, 
  Image as ImageIcon, 
  Rocket, 
  CheckCircle2, 
  Sparkles, 
  Facebook, 
  Linkedin, 
  Instagram, 
  Plus, 
  Trash2, 
  Loader2,
  Globe,
  MapPin,
  DollarSign,
  Calendar,
  Zap,
  ArrowRight,
  RefreshCcw,
  Download,
  Megaphone,
  Users
} from 'lucide-react';
import { useAuth } from '../lib/AuthContext';
import { AdCampaign, AdCreative, AdOffer, PREBUILT_OFFERS, AdPlatform } from '../types/ads';
import { AdService } from '../services/AdService';
import { motion, AnimatePresence } from 'motion/react';
import toast from 'react-hot-toast';

interface Props {
  onClose: () => void;
}

const STEPS = [
  { id: 'goal', title: 'Campaign Goal', icon: Target },
  { id: 'details', title: 'Campaign Details', icon: Layout },
  { id: 'ad_copy', title: 'Ad Creative', icon: Type },
  { id: 'review', title: 'Review & Launch', icon: Rocket },
];

const SERVICES = ['Kitchen Remodel', 'Bathroom Remodel', 'Roofing', 'Siding', 'Windows', 'Full Home Renovation', 'Deck & Patio'];

export default function AdCampaignBuilder({ onClose }: Props) {
  const { userData } = useAuth();
  const [currentStep, setCurrentStep] = useState(0);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isGeneratingImage, setIsGeneratingImage] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  const [campaign, setCampaign] = useState<Partial<AdCampaign>>({
    name: '',
    goal: 'lead_generation',
    service: SERVICES[0],
    location: { city: '', radius: 25 },
    budget: { daily: 50, currency: 'USD' },
    startDate: new Date().toISOString().split('T')[0],
    status: 'draft'
  });

  const [creative, setCreative] = useState<Partial<AdCreative>>({
    platform: 'facebook',
    copy: {
      primaryText: '',
      headline: '',
      description: '',
      cta: 'Get a Free Quote'
    },
    media: {
      type: 'image',
      urls: [],
      overlayText: ''
    },
    landingPageUrl: `https://${userData?.subdomain || 'your-site'}.closeproremodel.com/quote`
  });

  const [selectedOffer, setSelectedOffer] = useState<AdOffer>(PREBUILT_OFFERS[0]);

  const handleGenerateCopy = async () => {
    setIsGenerating(true);
    try {
      const copy = await AdService.generateAdCopy(campaign.service!, selectedOffer, creative.platform!);
      setCreative(prev => ({ ...prev, copy }));
      toast.success('Ad copy generated by AI!');
    } catch (error) {
      toast.error('Failed to generate ad copy');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleGenerateImage = async () => {
    setIsGeneratingImage(true);
    try {
      const imageUrl = await AdService.generateAdImage(campaign.service!, selectedOffer);
      setCreative(prev => ({
        ...prev,
        media: {
          ...prev.media!,
          urls: [imageUrl]
        }
      }));
      toast.success('Ad image generated by AI!');
    } catch (error) {
      toast.error('Failed to generate ad image');
    } finally {
      setIsGeneratingImage(false);
    }
  };

  const handleSave = async () => {
    if (!userData?.tenantId) return;
    setIsSaving(true);
    try {
      const campaignId = await AdService.createCampaign(userData.tenantId, campaign);
      await AdService.createAdCreative(userData.tenantId, {
        ...creative,
        campaignId
      });
      toast.success('Campaign created successfully!');
      onClose();
    } catch (error) {
      toast.error('Failed to save campaign');
    } finally {
      setIsSaving(false);
    }
  };

  const nextStep = () => setCurrentStep(prev => Math.min(prev + 1, STEPS.length - 1));
  const prevStep = () => setCurrentStep(prev => Math.max(prev - 1, 0));

  return (
    <div className="fixed inset-0 bg-navy/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <motion.div 
        initial={{ opacity: 0, scale: 0.95, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        className="bg-white w-full max-w-5xl h-[90vh] rounded-3xl shadow-2xl flex flex-col overflow-hidden"
      >
        {/* Header */}
        <div className="p-6 border-b border-gray-100 flex items-center justify-between bg-white flex-shrink-0">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 bg-blue-50 text-blue-600 rounded-2xl flex items-center justify-center">
              <Megaphone size={24} />
            </div>
            <div>
              <h2 className="text-xl font-bold text-navy">Campaign Builder</h2>
              <p className="text-sm text-gray-500">Step {currentStep + 1} of {STEPS.length}: {STEPS[currentStep].title}</p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-full transition-colors">
            <X size={24} className="text-gray-400" />
          </button>
        </div>

        {/* Progress Bar */}
        <div className="flex border-b border-gray-100 bg-gray-50/50">
          {STEPS.map((step, i) => (
            <div 
              key={step.id}
              className={`flex-1 py-3 px-4 flex items-center justify-center gap-2 border-b-2 transition-all ${
                i === currentStep ? 'border-blue-600 bg-white' : 
                i < currentStep ? 'border-green-500 bg-green-50/30' : 'border-transparent text-gray-400'
              }`}
            >
              <div className={`w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-bold ${
                i === currentStep ? 'bg-blue-600 text-white' : 
                i < currentStep ? 'bg-green-500 text-white' : 'bg-gray-200 text-gray-500'
              }`}>
                {i < currentStep ? <CheckCircle2 size={14} /> : i + 1}
              </div>
              <span className={`text-xs font-bold uppercase tracking-wider hidden md:inline ${
                i === currentStep ? 'text-blue-600' : i < currentStep ? 'text-green-600' : 'text-gray-400'
              }`}>
                {step.title}
              </span>
            </div>
          ))}
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-8">
          <AnimatePresence mode="wait">
            <motion.div
              key={currentStep}
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="max-w-3xl mx-auto"
            >
              {currentStep === 0 && (
                <div className="space-y-8">
                  <div className="text-center">
                    <h3 className="text-2xl font-bold text-navy mb-2">What is your primary goal?</h3>
                    <p className="text-gray-500">Select the objective that matches your business needs.</p>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {[
                      { id: 'lead_generation', title: 'Lead Generation', desc: 'Get contact info from potential customers.', icon: Users, color: 'blue' },
                      { id: 'website_traffic', title: 'Website Traffic', desc: 'Drive more visitors to your landing pages.', icon: Globe, color: 'green' },
                      { id: 'booking_appointments', title: 'Book Appointments', desc: 'Get homeowners to schedule consultations.', icon: Calendar, color: 'purple' },
                      { id: 'brand_awareness', title: 'Brand Awareness', desc: 'Increase visibility in your local area.', icon: Zap, color: 'orange' },
                    ].map((goal) => (
                      <button
                        key={goal.id}
                        onClick={() => setCampaign(prev => ({ ...prev, goal: goal.id as any }))}
                        className={`p-6 rounded-2xl border-2 text-left transition-all ${
                          campaign.goal === goal.id 
                            ? 'border-blue-600 bg-blue-50/50 ring-4 ring-blue-50' 
                            : 'border-gray-100 hover:border-blue-200 hover:bg-gray-50'
                        }`}
                      >
                        <div className={`w-12 h-12 bg-${goal.color}-100 text-${goal.color}-600 rounded-xl flex items-center justify-center mb-4`}>
                          <goal.icon size={24} />
                        </div>
                        <h4 className="font-bold text-navy mb-1">{goal.title}</h4>
                        <p className="text-sm text-gray-500 leading-relaxed">{goal.desc}</p>
                      </button>
                    ))}
                  </div>
                </div>
              )}

              {currentStep === 1 && (
                <div className="space-y-8">
                  <div className="text-center">
                    <h3 className="text-2xl font-bold text-navy mb-2">Campaign Details</h3>
                    <p className="text-gray-500">Define your service, location, and budget.</p>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="space-y-2">
                      <label className="text-sm font-bold text-navy">Campaign Name</label>
                      <input 
                        type="text" 
                        placeholder="e.g. Spring Kitchen Special"
                        value={campaign.name}
                        onChange={(e) => setCampaign(prev => ({ ...prev, name: e.target.value }))}
                        className="w-full px-4 py-3 bg-gray-50 border-none rounded-xl text-sm focus:ring-2 focus:ring-blue-500"
                      />
                    </div>
                    <div className="space-y-2">
                      <label className="text-sm font-bold text-navy">Service Category</label>
                      <select 
                        value={campaign.service}
                        onChange={(e) => setCampaign(prev => ({ ...prev, service: e.target.value }))}
                        className="w-full px-4 py-3 bg-gray-50 border-none rounded-xl text-sm focus:ring-2 focus:ring-blue-500"
                      >
                        {SERVICES.map(s => <option key={s} value={s}>{s}</option>)}
                      </select>
                    </div>
                    <div className="space-y-2">
                      <label className="text-sm font-bold text-navy">Target City</label>
                      <div className="relative">
                        <MapPin className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                        <input 
                          type="text" 
                          placeholder="e.g. Dallas, TX"
                          value={campaign.location?.city}
                          onChange={(e) => setCampaign(prev => ({ ...prev, location: { ...prev.location!, city: e.target.value } }))}
                          className="w-full pl-10 pr-4 py-3 bg-gray-50 border-none rounded-xl text-sm focus:ring-2 focus:ring-blue-500"
                        />
                      </div>
                    </div>
                    <div className="space-y-2">
                      <label className="text-sm font-bold text-navy">Daily Budget (USD)</label>
                      <div className="relative">
                        <DollarSign className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                        <input 
                          type="number" 
                          value={campaign.budget?.daily}
                          onChange={(e) => setCampaign(prev => ({ ...prev, budget: { ...prev.budget!, daily: parseInt(e.target.value) } }))}
                          className="w-full pl-10 pr-4 py-3 bg-gray-50 border-none rounded-xl text-sm focus:ring-2 focus:ring-blue-500"
                        />
                      </div>
                    </div>
                  </div>

                  <div className="p-6 bg-blue-50 rounded-2xl border border-blue-100">
                    <h4 className="font-bold text-blue-900 mb-4 flex items-center gap-2">
                      <Zap size={18} /> Select an Offer
                    </h4>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                      {PREBUILT_OFFERS.map((offer) => (
                        <button
                          key={offer.id}
                          onClick={() => setSelectedOffer(offer)}
                          className={`p-4 rounded-xl text-left transition-all ${
                            selectedOffer.id === offer.id 
                              ? 'bg-white border-2 border-blue-600 shadow-md' 
                              : 'bg-white/50 border-2 border-transparent hover:bg-white'
                          }`}
                        >
                          <p className="font-bold text-navy text-sm">{offer.title}</p>
                          <p className="text-xs text-gray-500 mt-1">{offer.description}</p>
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              )}

              {currentStep === 2 && (
                <div className="space-y-8">
                  <div className="text-center">
                    <h3 className="text-2xl font-bold text-navy mb-2">Ad Creative</h3>
                    <p className="text-gray-500">Generate high-converting copy and select your media.</p>
                  </div>

                  <div className="flex gap-4 p-1 bg-gray-100 rounded-xl w-fit mx-auto mb-8">
                    {[
                      { id: 'facebook', icon: Facebook, label: 'Facebook' },
                      { id: 'google', icon: Globe, label: 'Google' },
                      { id: 'instagram', icon: Instagram, label: 'Instagram' },
                      { id: 'linkedin', icon: Linkedin, label: 'LinkedIn' },
                    ].map((p) => (
                      <button
                        key={p.id}
                        onClick={() => setCreative(prev => ({ ...prev, platform: p.id as any }))}
                        className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-bold transition-all ${
                          creative.platform === p.id ? 'bg-white text-navy shadow-sm' : 'text-gray-500 hover:text-navy'
                        }`}
                      >
                        <p.icon size={16} />
                        {p.label}
                      </button>
                    ))}
                  </div>

                  <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                    {/* Editor */}
                    <div className="space-y-6">
                      <div className="flex items-center justify-between">
                        <h4 className="font-bold text-navy">Ad Copy</h4>
                        <button 
                          onClick={handleGenerateCopy}
                          disabled={isGenerating}
                          className="text-xs font-bold text-blue-600 flex items-center gap-1 hover:underline disabled:opacity-50"
                        >
                          {isGenerating ? <Loader2 className="animate-spin" size={14} /> : <Sparkles size={14} />}
                          AI Generate Copy
                        </button>
                      </div>
                      
                      <div className="space-y-4">
                        <div className="space-y-1">
                          <label className="text-xs font-bold text-gray-500 uppercase">Headline</label>
                          <input 
                            type="text" 
                            value={creative.copy?.headline}
                            onChange={(e) => setCreative(prev => ({ ...prev, copy: { ...prev.copy!, headline: e.target.value } }))}
                            className="w-full px-4 py-3 bg-gray-50 border-none rounded-xl text-sm focus:ring-2 focus:ring-blue-500"
                          />
                        </div>
                        <div className="space-y-1">
                          <label className="text-xs font-bold text-gray-500 uppercase">Primary Text</label>
                          <textarea 
                            rows={4}
                            value={creative.copy?.primaryText}
                            onChange={(e) => setCreative(prev => ({ ...prev, copy: { ...prev.copy!, primaryText: e.target.value } }))}
                            className="w-full px-4 py-3 bg-gray-50 border-none rounded-xl text-sm focus:ring-2 focus:ring-blue-500 resize-none"
                          />
                        </div>
                        <div className="space-y-1">
                          <label className="text-xs font-bold text-gray-500 uppercase">Call to Action</label>
                          <select 
                            value={creative.copy?.cta}
                            onChange={(e) => setCreative(prev => ({ ...prev, copy: { ...prev.copy!, cta: e.target.value } }))}
                            className="w-full px-4 py-3 bg-gray-50 border-none rounded-xl text-sm focus:ring-2 focus:ring-blue-500"
                          >
                            <option>Get a Free Quote</option>
                            <option>Book Now</option>
                            <option>Learn More</option>
                            <option>Contact Us</option>
                          </select>
                        </div>
                      </div>
                    </div>

                    {/* Preview */}
                    <div className="space-y-4">
                      <div className="flex items-center justify-between">
                        <h4 className="font-bold text-navy">Preview</h4>
                        <button 
                          onClick={handleGenerateImage}
                          disabled={isGeneratingImage}
                          className="text-xs font-bold text-blue-600 flex items-center gap-1 hover:underline disabled:opacity-50"
                        >
                          {isGeneratingImage ? <Loader2 className="animate-spin" size={14} /> : <Sparkles size={14} />}
                          AI Generate Image
                        </button>
                      </div>
                      <div className="bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm max-w-sm mx-auto">
                        <div className="p-3 flex items-center gap-2 border-b border-gray-100">
                          <div className="w-8 h-8 bg-blue-600 rounded-full flex items-center justify-center text-white font-bold text-xs">C</div>
                          <div>
                            <p className="text-xs font-bold">ClosePro Remodel</p>
                            <p className="text-[10px] text-gray-500">Sponsored</p>
                          </div>
                        </div>
                        <div className="p-3 space-y-2">
                          <p className="text-xs text-gray-800 whitespace-pre-wrap">{creative.copy?.primaryText || 'Your ad text will appear here...'}</p>
                        </div>
                        <div className="aspect-video bg-gray-100 flex items-center justify-center relative group">
                          {creative.media?.urls?.[0] ? (
                            <img src={creative.media.urls[0]} className="w-full h-full object-cover" />
                          ) : (
                            <div className="text-center p-6">
                              <ImageIcon className="mx-auto text-gray-300 mb-2" size={32} />
                              <p className="text-xs text-gray-400">Add an image or video</p>
                            </div>
                          )}
                          <div className="absolute bottom-0 left-0 right-0 p-4 bg-gradient-to-t from-black/60 to-transparent">
                            <p className="text-white font-bold text-sm">{creative.copy?.headline || 'Headline'}</p>
                          </div>
                        </div>
                        <div className="p-3 flex items-center justify-between bg-gray-50">
                          <p className="text-[10px] text-gray-500 uppercase font-bold">{creative.platform}.com</p>
                          <button className="px-4 py-1.5 bg-white border border-gray-200 rounded-md text-xs font-bold hover:bg-gray-50">
                            {creative.copy?.cta}
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {currentStep === 3 && (
                <div className="space-y-8">
                  <div className="text-center">
                    <h3 className="text-2xl font-bold text-navy mb-2">Ready to Launch?</h3>
                    <p className="text-gray-500">Review your campaign settings before publishing.</p>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <div className="space-y-6">
                      <div className="bg-gray-50 rounded-2xl p-6 space-y-4">
                        <h4 className="font-bold text-navy flex items-center gap-2">
                          <Layout size={18} className="text-blue-600" /> Campaign Summary
                        </h4>
                        <div className="space-y-3">
                          <div className="flex justify-between text-sm">
                            <span className="text-gray-500">Name</span>
                            <span className="font-bold text-navy">{campaign.name}</span>
                          </div>
                          <div className="flex justify-between text-sm">
                            <span className="text-gray-500">Goal</span>
                            <span className="font-bold text-navy capitalize">{campaign.goal?.replace('_', ' ')}</span>
                          </div>
                          <div className="flex justify-between text-sm">
                            <span className="text-gray-500">Service</span>
                            <span className="font-bold text-navy">{campaign.service}</span>
                          </div>
                          <div className="flex justify-between text-sm">
                            <span className="text-gray-500">Location</span>
                            <span className="font-bold text-navy">{campaign.location?.city} (+{campaign.location?.radius}mi)</span>
                          </div>
                          <div className="flex justify-between text-sm">
                            <span className="text-gray-500">Daily Budget</span>
                            <span className="font-bold text-blue-600">${campaign.budget?.daily}</span>
                          </div>
                        </div>
                      </div>

                      <div className="bg-gray-50 rounded-2xl p-6 space-y-4">
                        <h4 className="font-bold text-navy flex items-center gap-2">
                          <Globe size={18} className="text-blue-600" /> Landing Page
                        </h4>
                        <p className="text-xs text-gray-500 break-all">{creative.landingPageUrl}</p>
                        <button className="text-xs font-bold text-blue-600 hover:underline">Edit URL</button>
                      </div>
                    </div>

                    <div className="space-y-4">
                      <h4 className="font-bold text-navy">Final Ad Preview</h4>
                      <div className="bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm">
                        <div className="p-3 flex items-center gap-2 border-b border-gray-100">
                          <div className="w-8 h-8 bg-blue-600 rounded-full flex items-center justify-center text-white font-bold text-xs">C</div>
                          <div>
                            <p className="text-xs font-bold">ClosePro Remodel</p>
                            <p className="text-[10px] text-gray-500">Sponsored</p>
                          </div>
                        </div>
                        <div className="aspect-video bg-gray-100 flex items-center justify-center">
                          <ImageIcon className="text-gray-300" size={32} />
                        </div>
                        <div className="p-4 space-y-2">
                          <p className="text-sm font-bold text-navy">{creative.copy?.headline}</p>
                          <p className="text-xs text-gray-600 line-clamp-2">{creative.copy?.primaryText}</p>
                        </div>
                        <div className="p-3 bg-gray-50 flex justify-end">
                          <button className="px-4 py-1.5 bg-white border border-gray-200 rounded-md text-xs font-bold">
                            {creative.copy?.cta}
                          </button>
                        </div>
                      </div>
                      <div className="flex items-center gap-2 p-4 bg-green-50 text-green-700 rounded-xl text-xs">
                        <CheckCircle2 size={16} />
                        <span>Lead tracking and auto-followup are enabled for this campaign.</span>
                      </div>
                      <button 
                        onClick={() => {
                          const content = `Campaign: ${campaign.name}\nPlatform: ${creative.platform}\nHeadline: ${creative.copy?.headline}\nPrimary Text: ${creative.copy?.primaryText}\nCTA: ${creative.copy?.cta}\nLanding Page: ${creative.landingPageUrl}`;
                          const blob = new Blob([content], { type: 'text/plain' });
                          const url = URL.createObjectURL(blob);
                          const a = document.createElement('a');
                          a.href = url;
                          a.download = `${campaign.name?.replace(/\s+/g, '_')}_ad_assets.txt`;
                          a.click();
                          toast.success('Ad assets exported!');
                        }}
                        className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-white border border-gray-200 text-gray-600 rounded-xl font-bold hover:bg-gray-50 transition-all"
                      >
                        <Download size={18} />
                        Download Ad Assets (Export)
                      </button>
                    </div>
                  </div>
                </div>
              )}
            </motion.div>
          </AnimatePresence>
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-gray-100 flex items-center justify-between bg-white flex-shrink-0">
          <button 
            onClick={prevStep}
            disabled={currentStep === 0}
            className="flex items-center gap-2 px-6 py-3 text-gray-500 font-bold hover:bg-gray-100 rounded-xl transition-all disabled:opacity-0"
          >
            <ChevronLeft size={20} />
            Back
          </button>
          
          <div className="flex items-center gap-3">
            <button 
              onClick={onClose}
              className="px-6 py-3 text-gray-400 font-bold hover:text-gray-600"
            >
              Cancel
            </button>
            {currentStep === STEPS.length - 1 ? (
              <button 
                onClick={handleSave}
                disabled={isSaving}
                className="flex items-center gap-2 px-8 py-3 bg-electric text-white rounded-xl font-bold hover:shadow-lg hover:shadow-blue-500/30 transition-all disabled:opacity-50"
              >
                {isSaving ? <Loader2 className="animate-spin" size={20} /> : <Rocket size={20} />}
                Launch Campaign
              </button>
            ) : (
              <button 
                onClick={nextStep}
                className="flex items-center gap-2 px-8 py-3 bg-navy text-white rounded-xl font-bold hover:bg-blue-900 transition-all"
              >
                Next Step
                <ChevronRight size={20} />
              </button>
            )}
          </div>
        </div>
      </motion.div>
    </div>
  );
}
